{{- $_ := include "nodemedic-agent.requireTestCluster" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nodemedic-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "nodemedic-agent.labels" . | nindent 4 }}
  {{- if and (eq .Values.cloud.provider "aws") .Values.cloud.awsRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.cloud.awsRoleArn | quote }}
  {{- end }}
