/*
Copyright 2026 The New Relic Container Fabric authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// Phase enumerates the controller-driven phases of a NodeHealthDiagnosisAI.
// Schema authority: Scope 3 (Constitution Article II.2). For the hackathon
// the Evaluating/Evaluated phases are reserved for the post-hackathon eval
// agent and never written by the controller.
type Phase string

const (
	PhasePending     Phase = "Pending"
	PhaseDiagnosing  Phase = "Diagnosing"
	PhaseDiagnosed   Phase = "Diagnosed"
	PhaseEvaluating  Phase = "Evaluating"
	PhaseEvaluated   Phase = "Evaluated"
	PhaseActed       Phase = "Acted"
	PhaseFailed      Phase = "Failed"
)

// Provider names the cloud the Node runs on. Resolved by the controller
// from Node labels + spec.providerID per spec FR-2.
// +kubebuilder:validation:Enum=aws;azure
type Provider string

const (
	ProviderAWS   Provider = "aws"
	ProviderAzure Provider = "azure"
)

// EvidenceSource enumerates the evidence-source taxonomy used by the
// confidence gate (FR-6 / Constitution Article I.3).
// +kubebuilder:validation:Enum=nrql;ssh;kubectl;cloud;proc;log
type EvidenceSource string

// RecommendationAction is the agent's recommended response. The controller
// only ever performs Cordon (Constitution Article I.2). DrainAndCordon is
// honored as Cordon; NoAction skips cordon entirely and routes to
// HumanInLoop framing.
// +kubebuilder:validation:Enum=Cordon;DrainAndCordon;NoAction
type RecommendationAction string

const (
	RecommendationActionCordon         RecommendationAction = "Cordon"
	RecommendationActionDrainAndCordon RecommendationAction = "DrainAndCordon"
	RecommendationActionNoAction       RecommendationAction = "NoAction"
)

// RCACategory classifies the root-cause family produced by the agent.
// +kubebuilder:validation:Enum=Conntrack;FD;PID;Inode;Disk;DNS;IMDS;Kernel;Kubelet;Unknown
type RCACategory string

// ActionDecision is the controller's decision after the gate runs.
// +kubebuilder:validation:Enum=Applied;Skipped;HumanInLoop
type ActionDecision string

const (
	ActionDecisionApplied     ActionDecision = "Applied"
	ActionDecisionSkipped     ActionDecision = "Skipped"
	ActionDecisionHumanInLoop ActionDecision = "HumanInLoop"
)

// ActionOperation is the kube-side mutation actually performed.
// +kubebuilder:validation:Enum=cordon;noop
type ActionOperation string

const (
	ActionOperationCordon ActionOperation = "cordon"
	ActionOperationNoop   ActionOperation = "noop"
)

// CaseSpec carries everything the agent needs to start a diagnosis.
// All fields are required unless explicitly marked optional.
type CaseSpec struct {
	// CaseId is a UUIDv4 generated by the controller and echoed by the agent.
	// +kubebuilder:validation:Pattern=`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$`
	CaseId string `json:"caseId"`

	// NodeName is the apiserver Node name.
	// +kubebuilder:validation:MaxLength=253
	NodeName string `json:"nodeName"`

	// ClusterName is set per Helm install via the --cluster-name flag.
	// +kubebuilder:validation:MinLength=1
	ClusterName string `json:"clusterName"`

	// Provider names the cloud the Node runs on.
	Provider Provider `json:"provider"`

	// Region is the cloud region (e.g. us-east-2, eastus2).
	// +kubebuilder:validation:MinLength=1
	Region string `json:"region"`

	// InstanceId is the AWS instance-id or Azure VM name.
	// +kubebuilder:validation:MinLength=1
	InstanceId string `json:"instanceId"`

	// Trigger is the NodeCondition payload that woke the controller.
	Trigger TriggerSpec `json:"trigger"`
}

// TriggerSpec captures the NPD-flipped condition that started the case.
type TriggerSpec struct {
	// Type is the NodeCondition.type, e.g. ConntrackSaturated.
	// +kubebuilder:validation:MinLength=1
	Type string `json:"type"`

	// Reason is the NPD rule reason. May be empty.
	// +optional
	Reason string `json:"reason,omitempty"`

	// Message is the NPD rule message, truncated to 256 bytes.
	// +kubebuilder:validation:MaxLength=256
	// +optional
	Message string `json:"message,omitempty"`

	// ObservedAt is when NPD flipped the Condition to True.
	// +kubebuilder:validation:Format=date-time
	ObservedAt metav1.Time `json:"observedAt"`
}

// BudgetsSpec bounds the agent's loop. The controller writes these on
// Create; the agent enforces maxTurns and maxBudgetUSD; both sides
// honor the deadline (Constitution Article I.8).
type BudgetsSpec struct {
	// MaxTurns is the per-case turn cap.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:default=15
	// +optional
	MaxTurns int32 `json:"maxTurns,omitempty"`

	// MaxBudgetUSD is the per-case dollar cap, encoded as decimal-as-string
	// to avoid floating-point drift.
	// +kubebuilder:validation:Pattern=`^[0-9]+\.[0-9]{2}$`
	// +kubebuilder:default="0.50"
	// +optional
	MaxBudgetUSD string `json:"maxBudgetUSD,omitempty"`

	// Deadline is the hard wall-clock cap (RFC3339).
	// +kubebuilder:validation:Format=date-time
	// +optional
	Deadline *metav1.Time `json:"deadline,omitempty"`
}

// NodeHealthDiagnosisAISpec is the user-set input for a diagnosis case.
// Written by the controller (Scope 2); read by the agent (Scope 3).
type NodeHealthDiagnosisAISpec struct {
	Case    CaseSpec    `json:"case"`
	Budgets BudgetsSpec `json:"budgets"`
}

// EvidenceItem is one citation backing the agent's diagnosis. The
// confidence gate (FR-6) requires at least two distinct sources for
// auto-cordon to fire.
type EvidenceItem struct {
	// Source is the evidence-source taxonomy entry.
	Source EvidenceSource `json:"source"`

	// Ref is the query / command / path that produced the evidence.
	// +optional
	Ref string `json:"ref,omitempty"`

	// Result is the raw result, truncated to 4 KB.
	// +kubebuilder:validation:MaxLength=4096
	// +optional
	Result string `json:"result,omitempty"`

	// ObservedAt is when the evidence was captured.
	// +kubebuilder:validation:Format=date-time
	// +optional
	ObservedAt *metav1.Time `json:"observedAt,omitempty"`
}

// Recommendation is the agent's recommended response.
type Recommendation struct {
	Action RecommendationAction `json:"action"`

	// Reason is a short human-readable justification.
	// +optional
	Reason string `json:"reason,omitempty"`
}

// AuditLogRef points at the audit JSONL produced by the agent's
// PreToolUse hook (Constitution Article I.7).
type AuditLogRef struct {
	// ObjectStore is e.g. s3://... or a local path.
	// +optional
	ObjectStore string `json:"objectStore,omitempty"`
}

// Diagnosis is the agent's output. Written once by Scope 3.
type Diagnosis struct {
	// RootCause is a one-paragraph RCA.
	// +optional
	RootCause string `json:"rootCause,omitempty"`

	// RCACategory classifies the failure family.
	// +optional
	RCACategory RCACategory `json:"rcaCategory,omitempty"`

	// Confidence is in [0.0, 1.0].
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=1
	// +optional
	Confidence float64 `json:"confidence,omitempty"`

	// Evidence is the supporting citations. Min 2 distinct sources for
	// the gate to pass.
	// +optional
	Evidence []EvidenceItem `json:"evidence,omitempty"`

	// Recommendation is the agent's recommended response.
	// +optional
	Recommendation *Recommendation `json:"recommendation,omitempty"`

	// AuditLogRef points at the PreToolUse audit JSONL.
	// +optional
	AuditLogRef *AuditLogRef `json:"auditLogRef,omitempty"`

	// ModelUsed names the LLM that produced the diagnosis.
	// +optional
	ModelUsed string `json:"modelUsed,omitempty"`

	// TurnsUsed is the count of agent loop turns consumed.
	// +optional
	TurnsUsed int32 `json:"turnsUsed,omitempty"`

	// CostUSD is the agent-loop dollar cost, decimal-as-string.
	// +optional
	CostUSD string `json:"costUSD,omitempty"`

	// CompletedAt is when the agent finished writing the diagnosis.
	// +kubebuilder:validation:Format=date-time
	// +optional
	CompletedAt *metav1.Time `json:"completedAt,omitempty"`
}

// Evaluation is reserved for the post-hackathon eval agent; in v1 the
// controller never reads or writes it. Present so the v1 controller can
// coexist with a future eval agent without a CRD bump.
type Evaluation struct {
	// +optional
	AgreesWithDiagnosis *bool `json:"agreesWithDiagnosis,omitempty"`
	// +optional
	Confidence float64 `json:"confidence,omitempty"`
	// +optional
	Notes string `json:"notes,omitempty"`
	// +optional
	CompletedAt *metav1.Time `json:"completedAt,omitempty"`
}

// SlackNotification records a successful Slack post for audit purposes.
type SlackNotification struct {
	// +optional
	Channel string `json:"channel,omitempty"`
	// +optional
	Ts string `json:"ts,omitempty"`
	// +optional
	Permalink string `json:"permalink,omitempty"`
}

// Notifications collects the side-channel notifications the controller
// fired for this case. Slack is the only notifier in v1; PagerDuty is
// reserved for post-hackathon.
type Notifications struct {
	// +optional
	Slack *SlackNotification `json:"slack,omitempty"`
}

// ActionStatus is the controller's record of what it did. Written by
// Scope 2. Mirrors spec FR-6 / FR-9.
type ActionStatus struct {
	// +optional
	Decision ActionDecision `json:"decision,omitempty"`
	// +optional
	Operation ActionOperation `json:"operation,omitempty"`
	// +optional
	// +kubebuilder:validation:Format=date-time
	AppliedAt *metav1.Time `json:"appliedAt,omitempty"`
	// +optional
	Notifications *Notifications `json:"notifications,omitempty"`
}

// NodeHealthDiagnosisAIStatus is the observed state of a case.
type NodeHealthDiagnosisAIStatus struct {
	// Phase is the controller-driven phase machine state. See spec FR-5.
	// +kubebuilder:validation:Enum=Pending;Diagnosing;Diagnosed;Evaluating;Evaluated;Acted;Failed
	// +optional
	Phase Phase `json:"phase,omitempty"`

	// Conditions is the standard k8s Condition history. Every phase
	// transition adds or updates an entry (NFR-7 audit trail).
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`

	// Diagnosis is written once by the agent.
	// +optional
	Diagnosis *Diagnosis `json:"diagnosis,omitempty"`

	// Evaluation is reserved for post-hackathon. Not written or read in v1.
	// +optional
	Evaluation *Evaluation `json:"evaluation,omitempty"`

	// Action is the controller's record of what it did.
	// +optional
	Action *ActionStatus `json:"action,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=nhd
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`
// +kubebuilder:printcolumn:name="Node",type=string,JSONPath=`.spec.case.nodeName`
// +kubebuilder:printcolumn:name="Provider",type=string,JSONPath=`.spec.case.provider`
// +kubebuilder:printcolumn:name="Confidence",type=number,JSONPath=`.status.diagnosis.confidence`
// +kubebuilder:printcolumn:name="Decision",type=string,JSONPath=`.status.action.decision`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// NodeHealthDiagnosisAI is one diagnosis case for one (Node, NodeCondition) pair.
type NodeHealthDiagnosisAI struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NodeHealthDiagnosisAISpec   `json:"spec,omitempty"`
	Status NodeHealthDiagnosisAIStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NodeHealthDiagnosisAIList is a list of NodeHealthDiagnosisAI cases.
type NodeHealthDiagnosisAIList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NodeHealthDiagnosisAI `json:"items"`
}

// Compile-time interface assertions; these break the build early if the
// generated DeepCopy methods drift away from runtime.Object.
var (
	_ runtime.Object = (*NodeHealthDiagnosisAI)(nil)
	_ runtime.Object = (*NodeHealthDiagnosisAIList)(nil)
)
