//go:build !ignore_autogenerated

/*
Copyright 2026 The New Relic Container Fabric authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionStatus) DeepCopyInto(out *ActionStatus) {
	*out = *in
	if in.AppliedAt != nil {
		in, out := &in.AppliedAt, &out.AppliedAt
		*out = (*in).DeepCopy()
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(Notifications)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionStatus.
func (in *ActionStatus) DeepCopy() *ActionStatus {
	if in == nil {
		return nil
	}
	out := new(ActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogRef) DeepCopyInto(out *AuditLogRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogRef.
func (in *AuditLogRef) DeepCopy() *AuditLogRef {
	if in == nil {
		return nil
	}
	out := new(AuditLogRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetsSpec) DeepCopyInto(out *BudgetsSpec) {
	*out = *in
	if in.Deadline != nil {
		in, out := &in.Deadline, &out.Deadline
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetsSpec.
func (in *BudgetsSpec) DeepCopy() *BudgetsSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaseSpec) DeepCopyInto(out *CaseSpec) {
	*out = *in
	in.Trigger.DeepCopyInto(&out.Trigger)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaseSpec.
func (in *CaseSpec) DeepCopy() *CaseSpec {
	if in == nil {
		return nil
	}
	out := new(CaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Diagnosis) DeepCopyInto(out *Diagnosis) {
	*out = *in
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = make([]EvidenceItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Recommendation != nil {
		in, out := &in.Recommendation, &out.Recommendation
		*out = new(Recommendation)
		**out = **in
	}
	if in.AuditLogRef != nil {
		in, out := &in.AuditLogRef, &out.AuditLogRef
		*out = new(AuditLogRef)
		**out = **in
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Diagnosis.
func (in *Diagnosis) DeepCopy() *Diagnosis {
	if in == nil {
		return nil
	}
	out := new(Diagnosis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Evaluation) DeepCopyInto(out *Evaluation) {
	*out = *in
	if in.AgreesWithDiagnosis != nil {
		in, out := &in.AgreesWithDiagnosis, &out.AgreesWithDiagnosis
		*out = new(bool)
		**out = **in
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Evaluation.
func (in *Evaluation) DeepCopy() *Evaluation {
	if in == nil {
		return nil
	}
	out := new(Evaluation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceItem) DeepCopyInto(out *EvidenceItem) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceItem.
func (in *EvidenceItem) DeepCopy() *EvidenceItem {
	if in == nil {
		return nil
	}
	out := new(EvidenceItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHealthDiagnosisAI) DeepCopyInto(out *NodeHealthDiagnosisAI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHealthDiagnosisAI.
func (in *NodeHealthDiagnosisAI) DeepCopy() *NodeHealthDiagnosisAI {
	if in == nil {
		return nil
	}
	out := new(NodeHealthDiagnosisAI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeHealthDiagnosisAI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHealthDiagnosisAIList) DeepCopyInto(out *NodeHealthDiagnosisAIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeHealthDiagnosisAI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHealthDiagnosisAIList.
func (in *NodeHealthDiagnosisAIList) DeepCopy() *NodeHealthDiagnosisAIList {
	if in == nil {
		return nil
	}
	out := new(NodeHealthDiagnosisAIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeHealthDiagnosisAIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHealthDiagnosisAISpec) DeepCopyInto(out *NodeHealthDiagnosisAISpec) {
	*out = *in
	in.Case.DeepCopyInto(&out.Case)
	in.Budgets.DeepCopyInto(&out.Budgets)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHealthDiagnosisAISpec.
func (in *NodeHealthDiagnosisAISpec) DeepCopy() *NodeHealthDiagnosisAISpec {
	if in == nil {
		return nil
	}
	out := new(NodeHealthDiagnosisAISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHealthDiagnosisAIStatus) DeepCopyInto(out *NodeHealthDiagnosisAIStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Diagnosis != nil {
		in, out := &in.Diagnosis, &out.Diagnosis
		*out = new(Diagnosis)
		(*in).DeepCopyInto(*out)
	}
	if in.Evaluation != nil {
		in, out := &in.Evaluation, &out.Evaluation
		*out = new(Evaluation)
		(*in).DeepCopyInto(*out)
	}
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(ActionStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHealthDiagnosisAIStatus.
func (in *NodeHealthDiagnosisAIStatus) DeepCopy() *NodeHealthDiagnosisAIStatus {
	if in == nil {
		return nil
	}
	out := new(NodeHealthDiagnosisAIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Notifications) DeepCopyInto(out *Notifications) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackNotification)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Notifications.
func (in *Notifications) DeepCopy() *Notifications {
	if in == nil {
		return nil
	}
	out := new(Notifications)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Recommendation) DeepCopyInto(out *Recommendation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Recommendation.
func (in *Recommendation) DeepCopy() *Recommendation {
	if in == nil {
		return nil
	}
	out := new(Recommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackNotification) DeepCopyInto(out *SlackNotification) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackNotification.
func (in *SlackNotification) DeepCopy() *SlackNotification {
	if in == nil {
		return nil
	}
	out := new(SlackNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerSpec) DeepCopyInto(out *TriggerSpec) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerSpec.
func (in *TriggerSpec) DeepCopy() *TriggerSpec {
	if in == nil {
		return nil
	}
	out := new(TriggerSpec)
	in.DeepCopyInto(out)
	return out
}
