{{- $_ := include "nodemedic-oncall-ui.requireTestCluster" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nodemedic-oncall-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "nodemedic-oncall-ui.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets: {{- toYaml . | nindent 2 }}
{{- end }}
